### ISSUE TITLE
Need a way to use these designs in the old prototyping kit and old frontend (eg. divorce production code)

### ISSUE THREAD

**Issue by gonogo** [hmcts/design-system#24]

**Comment by gonogo** [comment]
We need a way to separate the sass, js, nunjucks, and macros for the hmcts specific components so that they can work in the old prototyping kit and the existing code currently in production which does not (and never will) use the new design system.

**Comment by adamsilver** [comment]
Check this out:
https://govuk-prototype-kit.herokuapp.com/docs/backwards-compatibility
