### ISSUE TITLE
Red used in error banner doesn't match govuk-error-colour

### ISSUE THREAD

**Issue by edwardhorsford** [hmcts/design-system#28]
The red appears lighter than govuk-error-colour:
 
<img width="1032" alt="screenshot 2019-01-18 at 12 39 25" src="https://user-images.githubusercontent.com/2204224/51387815-5ecdea00-1b1f-11e9-9739-c795c7b2479f.png">

govuk-error-colour:
<img width="683" alt="screenshot 2019-01-18 at 12 48 44" src="https://user-images.githubusercontent.com/2204224/51387826-6c836f80-1b1f-11e9-8892-35db89ccbacd.png">

**Comment by adamsilver** [comment]
Fixed.
